---
title: "Logit models of production data with Bayesian predictive modelling"
author: "Annie Helms (annie_helms@berkeley.edu)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "cairo_pdf", out.height = 600)
options(scipen = 999) # avoid scientific notation
```

Library packages

```{r message = FALSE, warning = FALSE}
library(lmerTest) #mixed effects linear regression
library(dplyr)
library(ggplot2)
library(Cairo)
library(effects)
library(ragg)
library(gridExtra)
library(ggside)
library(sjPlot)
library(emmeans)
library(ggstatsplot)
library(pscl)
library(bayesplot)
library(brms)
library(ggtext)
library(kableExtra) # formats dataframes in html output
```

Set working directory.

```{r message = FALSE, echo = FALSE}
setwd("C:/Users/atarv/Documents/github/diss/production/")
```


```{r}
options(width = 10000)
data = read.csv("data/big_PCA_forR.csv", 
                  stringsAsFactors = TRUE)
head(data)
```

## Catalan production

```{r}
cat = data %>%
  filter(Language=="cat")
head(cat)

```

```{r}
cat_formula = "stress ~ dur_period*pc1*syllable + dur_period*pc2*syllable + f0*pc1*syllable + f0*pc2*syllable + vowel_periph*pc1*syllable + vowel_periph*pc2*syllable + (dur_period * syllable + f0 * syllable + vowel_periph * syllable|partID)"

cat_priors <- get_prior(cat_formula,cat,family=bernoulli())

cat_model <- brm(formula=bf(cat_formula,autocor = ~ 0),data=cat, family=bernoulli(), 
            prior=cat_priors, cores = 8, save_pars = save_pars(all = TRUE), iter=4000)
```

Examine results

```{r}
summary(cat_model)
bayes_R2(cat_model)
```

Visualize results

```{r}
cat_posterior <- as.array(cat_model)  # prepare to plot the brm result
dim(cat_posterior)
dimnames(cat_posterior)$variable[1:30]
```

```{r}
cat_coeff_plot = mcmc_areas(cat_posterior, pars = c("b_dur_period", "b_pc1", "b_syllableult", "b_pc2", "b_f0",  "b_vowel_periph", "b_dur_period:pc1",  "b_dur_period:syllableult", "b_pc1:syllableult", "b_dur_period:pc2", "b_syllableult:pc2", "b_pc1:f0", "b_syllableult:f0", "b_pc2:f0", "b_pc1:vowel_periph", "b_syllableult:vowel_periph", "b_pc2:vowel_periph", "b_dur_period:pc1:syllableult", "b_dur_period:syllableult:pc2", "b_pc1:syllableult:f0", "b_syllableult:pc2:f0", "b_pc1:syllableult:vowel_periph", "b_syllableult:pc2:vowel_periph"), 
          prob = 0.8, # 80% intervals
          prob_outer = 0.95, # 95%
          point_est = "median") +
scale_y_discrete(labels=c("Ultimate syllable:PC2:Vowel peripherality", "PC1:Ultimate syllable: Vowel peripherality", "Ultimate syllable:PC2:F0", "PC1:Ultimate syllable:F0", "Duration (periodic):Ultimate syllable:PC2", "Duration (periodic):PC1:Ultimate syllable", "PC2:Vowel peripherality", "Ultimate syllable:Vowel peripherality", "PC1:Vowel peripherality", "PC2:F0", "Ultimate syllable:F0", "PC1:F0", "Ultimate syllable:PC2", "Duration (periodic):PC2", "PC1:Ultimate syllable","Duration (periodic):Ultimate syllable", "Duration (periodic):PC1", "Vowel peripherality", "F0","PC2","Ultimate syllable", "PC1", "Duration (periodic)"), limits=rev) +
  labs(title = "Coefficients of Catalan production", x ="Coefficient, sd(Stress)") +theme(plot.title=element_text(hjust = 0.5))
cat_coeff_plot
```
```{r}
cairo_pdf("figures/cat_coeff.pdf", family = "serif", width = 8, height = 6)
cat_coeff_plot
dev.off()
```

```{r}
cat_syllable_f0 = conditional_effects(cat_model, effects = "f0:syllable", int_conditions = "syllable")
```

```{r}
cat_syllable_f0_plot = plot(cat_syllable_f0, plot = FALSE)[[1]] + labs(title = "Catalan production", x = "F0", y = "Proportion stressed") + guides(color=guide_legend(title="Syllable"), fill = 'none') +
  scale_color_discrete(labels=c('Penultimate', 'Ultimate')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")
cat_syllable_f0_plot
```
```{r}
cairo_pdf("figures/cat_syllable_f0_production.pdf", family = "serif", width = 8, height = 6)
cat_syllable_f0_plot
dev.off()
```


```{r}
emt <- emtrends(cat_model, "syllable", var = "f0")
emt
pairs(emt)
```

```{r}
cat_syllable_vowel = conditional_effects(cat_model, effects = "vowel_periph:syllable", int_conditions = "syllable")
```

```{r}
cat_syllable_vowel_plot = plot(cat_syllable_vowel, plot = FALSE)[[1]] + labs(title = "Catalan production", x = "Vowel peripherality", y = "Proportion stressed") + guides(color=guide_legend(title="Syllable"), fill = 'none') +
  scale_color_discrete(labels=c('Penultimate', 'Ultimate')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")
cat_syllable_vowel_plot
```
```{r}
cairo_pdf("figures/cat_syllable_vowel_production.pdf", family = "serif", width = 8, height = 6)
cat_syllable_vowel_plot
dev.off()
```

```{r}
emt <- emtrends(cat_model, "syllable", var = "vowel_periph")
emt
pairs(emt)
```
```{r}
cat_dur_pc1 = conditional_effects(cat_model, effects = "pc1:dur_period", int_conditions = "pc1")
```

```{r}
cat_dur_pc1_plot = plot(cat_dur_pc1, plot = FALSE)[[1]] + labs(title = "Catalan production", x = "PC1", y = "Proportion stressed") + guides(color=guide_legend(title="Duration (periodic)"), fill = 'none') +
  scale_color_discrete(labels=c('+1 SD', 'mean', '-1 SD')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")
cat_dur_pc1_plot
```

```{r}
cairo_pdf("figures/cat_dur_pc1_production.pdf", family = "serif", width = 8, height = 6)
cat_dur_pc1_plot
dev.off()
```
```{r}
cat %>%
  select(pc1)%>%
  summarize(mean = mean(pc1),
            low_sd = mean(pc1)-sd(pc1),
            high_sd = mean(pc1)+sd(pc1))
  
```

```{r}
cat %>%
  select(vowel_periph)%>%
  summarize(mean = mean(vowel_periph),
            low_sd = mean(vowel_periph)-sd(vowel_periph),
            high_sd = mean(vowel_periph)+sd(vowel_periph))
  
```

```{r}
conditions_by_part = data.frame(vowel_periph = c(-0.9406, 0.2472, 1.4350))
```

```{r}
by_subject = conditional_effects(cat_model, effects="partID:syllable", re_formula = NULL, conditions = conditions_by_part)
```


```{r}
cat_vowel_part_plot = plot(by_subject, plot = FALSE)[[1]] + labs(title = "Catalan production", x = "Participant", y = "Proportion stressed") +
  # guides(color=guide_legend(title="Syllable"), fill = 'none') +
  # scale_color_discrete(labels=c('Penultimate', 'Ultimate')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")

cat_vowel_part_plot$data$cond__ <- ifelse(cat_vowel_part_plot$data$cond__ == "1", "Vowel peripherality (-1 SD)",
ifelse(cat_vowel_part_plot$data$cond__ == "2", "Vowel peripherality (mean)",
ifelse(cat_vowel_part_plot$data$cond__ == "3", "Vowel peripherality (+1 SD)", 99)))
cat_vowel_part_plot$facet$params$ncol=1

cat_vowel_part_plot$data$cond__ <- factor(cat_vowel_part_plot$data$cond__, levels = c("Vowel peripherality (-1 SD)", "Vowel peripherality (mean)", "Vowel peripherality (+1 SD)"))

cat_vowel_part_plot
```

```{r}
conditions_by_syllable = data.frame(syllable = c('pen', 'ult'))
```

```{r}
by_subject_syllable = conditional_effects(cat_model, effects="partID:vowel_periph", re_formula = NULL, conditions = conditions_by_syllable)
```


```{r}
cat_vowel_part_plot_syllable = plot(by_subject_syllable, plot = FALSE)[[1]] + labs(title = "Catalan production", x = "Participant", y = "Proportion stressed") +
  guides(color=guide_legend(title="Vowel peripherality"), fill = 'none') +
  scale_color_discrete(breaks = c(-0.94, 0.25, 1.43), labels=c('-1 SD', 'Mean', '+1 SD')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  scale_x_discrete(labels=seq(1, 49, by=1))

cat_vowel_part_plot_syllable$data$cond__ <- ifelse(cat_vowel_part_plot_syllable$data$cond__ == "1", "Penultimate syllable",
ifelse(cat_vowel_part_plot_syllable$data$cond__ == "2", "Ultimate syllable", 99))
cat_vowel_part_plot_syllable$facet$params$ncol=1

# cat_vowel_part_plot$data$cond__ <- factor(cat_vowel_part_plot$data$cond__, levels = c("Vowel peripherality (-1 SD)", "Vowel peripherality (mean)", "Vowel peripherality (+1 SD)"))

cat_vowel_part_plot_syllable
```
```{r}
cairo_pdf("figures/cat_vowel_part_plot_syllable.pdf", family = "serif", width = 20, height = 10)
cat_vowel_part_plot_syllable
dev.off()
```


```{r}
conditions = data.frame(pc1 = c(-5.394, -0.4445, 4.505))
cat_dur_pc1_syllable = conditional_effects(cat_model, effects = "dur_period:syllable", conditions = conditions)
```

```{r}
cat_dur_pc1_syllable_plot = plot(cat_dur_pc1_syllable, plot = FALSE)[[1]] + labs(title = "Catalan production", x = "Duration (periodic)", y = "Proportion stressed") +
  guides(color=guide_legend(title="Syllable"), fill = 'none') +
  scale_color_discrete(labels=c('Penultimate', 'Ultimate')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")

cat_dur_pc1_syllable_plot$data$cond__ <- ifelse(cat_dur_pc1_syllable_plot$data$cond__ == "1", "PC1 (-1 SD)",
ifelse(cat_dur_pc1_syllable_plot$data$cond__ == "2", "PC1 (mean)",
ifelse(cat_dur_pc1_syllable_plot$data$cond__ == "3", "PC1 (+1 SD)", 99)))


cat_dur_pc1_syllable_plot$data$cond__ <- factor(cat_dur_pc1_syllable_plot$data$cond__, levels = c("PC1 (-1 SD)", "PC1 (mean)", "PC1 (+1 SD)"))

cat_dur_pc1_syllable_plot
```

```{r}
cairo_pdf("figures/cat_dur_pc1_syllable_production.pdf", family = "serif", width = 8, height = 6)
cat_dur_pc1_syllable_plot
dev.off()
```

```{r}
emt <- emtrends(cat_model, "syllable", var = "pc1")
emt
pairs(emt)
```


```{r}
check = cat %>%
  mutate(pc1_binary = case_when(
    pc1 < 0   ~ "low" ,
    pc1 >0 ~ "high"))

check %>%
  group_by(pc1_binary, syllable, stress) %>% 
  count()
```



