---
title: "Logit models of production data with Bayesian predictive modelling"
author: "Annie Helms (annie_helms@berkeley.edu)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "cairo_pdf", out.height = 600)
options(scipen = 999) # avoid scientific notation
```

Library packages

```{r message = FALSE, warning = FALSE}
library(lmerTest) #mixed effects linear regression
library(dplyr)
library(ggplot2)
library(Cairo)
library(effects)
library(ragg)
library(gridExtra)
library(ggside)
library(sjPlot)
library(emmeans)
library(ggstatsplot)
library(pscl)
library(bayesplot)
library(brms)
library(ggtext)
library(kableExtra) # formats dataframes in html output
```

Set working directory.

```{r message = FALSE, echo = FALSE}
setwd("C:/Users/atarv/Documents/github/diss/production/")
```


```{r}
options(width = 10000)
data = read.csv("data/big_PCA_forR_f1f2.csv", 
                  stringsAsFactors = TRUE)
head(data)
```

## Spanish production

```{r}
spa = data %>%
  filter(Language=="spa")
head(spa)

```

```{r}
spa_formula = "stress ~ v_dur_period*pc1*syllable + v_dur_period*pc2*syllable + f0*pc1*syllable + f0*pc2*syllable + syl_dur*pc1*syllable + syl_dur*pc2*syllable + sF1_norm_center*pc1*syllable + sF1_norm_center*pc2*syllable + sF2_norm_center*pc1*syllable + sF2_norm_center*pc2*syllable + (v_dur_period * syllable + f0 * syllable + syl_dur * syllable + sF1_norm_center*syllable + sF2_norm_center*syllable|partID)"

spa_priors <- get_prior(spa_formula,spa,family=bernoulli())

spa_model <- brm(formula=bf(spa_formula,autocor = ~ 0),data=spa, family=bernoulli(), 
            prior=spa_priors, cores = 8, save_pars = save_pars(all = TRUE), iter=4000)
```

Examine results

```{r}
summary(spa_model)
bayes_R2(spa_model)
```

Visualize results

```{r}
spa_posterior <- as.array(spa_model)  # prepare to plot the brm result
dim(spa_posterior)
dimnames(spa_posterior)$variable[1:50]
```

```{r}
spa_coeff_plot = mcmc_areas(spa_posterior, pars = c("b_v_dur_period", "b_pc1", "b_syllableult", "b_pc2", "b_f0", "b_syl_dur", "b_sF1_norm_center", "b_sF2_norm_center", "b_v_dur_period:pc1", "b_v_dur_period:syllableult", "b_pc1:syllableult", "b_v_dur_period:pc2", "b_syllableult:pc2", "b_pc1:f0", "b_syllableult:f0", "b_pc2:f0", "b_pc1:syl_dur", "b_syllableult:syl_dur", "b_pc2:syl_dur", "b_pc1:sF1_norm_center", "b_syllableult:sF1_norm_center", "b_pc2:sF1_norm_center","b_pc1:sF2_norm_center", "b_syllableult:sF2_norm_center", "b_pc2:sF2_norm_center", "b_v_dur_period:pc1:syllableult", "b_v_dur_period:syllableult:pc2", "b_pc1:syllableult:f0", "b_syllableult:pc2:f0", "b_pc1:syllableult:syl_dur", "b_syllableult:pc2:syl_dur", "b_pc1:syllableult:sF1_norm_center", "b_syllableult:pc2:sF1_norm_center", "b_pc1:syllableult:sF2_norm_center", "b_syllableult:pc2:sF2_norm_center"), 
          prob = 0.8, # 80% intervals
          prob_outer = 0.95, # 95%
          point_est = "median") +
scale_y_discrete(labels=c("Ultimate syllable:PC2:F2", "PC1:Ultimate syllable:F2", "Ultimate syllable:PC2:F1", "PC1:Ultimate syllable:F1", "Ultimate syllable:PC2:Syllable duration", "PC1:Ultimate syllable:Syllable duration", "Ultimate syllable:PC2:F0", "PC1:Ultimate syllable:F0", "Vowel duration (periodic):Ultimate syllable:PC2", "Vowel duration (periodic):PC1:Ultimate syllable", "PC2:F2", "Ultimate syllable:F2","PC1:F2", "PC2:F1", "Ultimate syllable:F1", "PC1:F1", "PC2:Syllable duration", "Ultimate syllable:Syllable duration", "PC1:Syllable duration", "PC2:F0", "Ultimate syllable:F0", "PC1:F0", "Ultimate syllable:PC2", "Vowel duration (periodic):PC2", "PC1:Ultimate syllable", "Vowel duration (periodic):Ultimate syllable", "Vowel duration (periodic):PC1", "F2", "F1", "Syllable duration", "F0", "PC2", "Ultimate syllable", "PC1", "Vowel duration (periodic)"), limits=rev) +
  labs(title = "Coefficients of Spanish production", x ="Coefficient, sd(Stress)") +theme(plot.title=element_text(hjust = 0.5))
spa_coeff_plot
```
```{r}
cairo_pdf("figures/spa_coeff.pdf", family = "serif", width = 8, height = 6)
spa_coeff_plot
dev.off()
```

```{r}
spa_syllable_f0 = conditional_effects(spa_model, effects = "f0:syllable", int_conditions = "syllable")
```

```{r}
spa_syllable_f0_plot = plot(spa_syllable_f0, plot = FALSE)[[1]] + labs(title = "Spanish production", x = "F0", y = "Proportion stressed") + guides(color=guide_legend(title="Syllable"), fill = 'none') +
  scale_color_discrete(labels=c('Penultimate', 'Ultimate')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")
spa_syllable_f0_plot
```


```{r}
cairo_pdf("figures/spa_syllable_f0_production.pdf", family = "serif", width = 8, height = 6)
spa_syllable_f0_plot
dev.off()
```


```{r}
emt <- emtrends(spa_model, "syllable", var = "f0")
emt
pairs(emt)
```

```{r}
emt <- emtrends(spa_model, "syllable", var = "sF1_norm_center")
emt
pairs(emt)
```

```{r}
spa_syllable_f1 = conditional_effects(spa_model, effects = "sF1_norm_center:syllable", int_conditions = "syllable")
```

```{r}
spa_syllable_f1_plot = plot(spa_syllable_f1, plot = FALSE)[[1]] + labs(title = "Spanish production", x = "Normalized F1", y = "Proportion stressed") + guides(color=guide_legend(title="Syllable"), fill = 'none') +
  scale_color_discrete(labels=c('Penultimate', 'Ultimate')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")
spa_syllable_f1_plot
```
```{r}
cairo_pdf("figures/spa_syllable_f1_production.pdf", family = "serif", width = 8, height = 6)
spa_syllable_f1_plot
dev.off()
```
```{r}
emt <- emtrends(spa_model, "syllable", var = "sF2_norm_center")
emt
pairs(emt)
```


```{r}
spa_syllable_f2 = conditional_effects(spa_model, effects = "sF2_norm_center:syllable", int_conditions = "syllable")
```

```{r}
spa_syllable_f2_plot = plot(spa_syllable_f2, plot = FALSE)[[1]] + labs(title = "Spanish production", x = "Normalized F2", y = "Proportion stressed") + guides(color=guide_legend(title="Syllable"), fill = 'none') +
  scale_color_discrete(labels=c('Penultimate', 'Ultimate')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")
spa_syllable_f2_plot
```
```{r}
cairo_pdf("figures/spa_syllable_f2_production.pdf", family = "serif", width = 8, height = 6)
spa_syllable_f2_plot
dev.off()
```

```{r}
spa_f2_pc1 = conditional_effects(spa_model, effects = "pc1:sF2_norm_center", int_conditions = "pc1")
```

```{r}
spa_f2_pc1_plot = plot(spa_f2_pc1, plot = FALSE)[[1]] + labs(title = "Spanish production", x = "PC1", y = "Proportion stressed") + guides(color=guide_legend(title="Normalized F2"), fill = 'none') +
  scale_color_discrete(labels=c('+1 SD', 'mean', '-1 SD')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")
spa_f2_pc1_plot
```


```{r}
spa_dur_pc1 = conditional_effects(spa_model, effects = "pc1:v_dur_period", int_conditions = "pc1")
```

```{r}
spa_dur_pc1_plot = plot(spa_dur_pc1, plot = FALSE)[[1]] + labs(title = "Spanish production", x = "PC1", y = "Proportion stressed") + guides(color=guide_legend(title="Vowel duration (periodic)"), fill = 'none') +
 scale_color_discrete(breaks = c(-2.52, 0.06, 2.64), labels=c('-1 SD', 'mean', '+1 SD')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")
spa_dur_pc1_plot
```

```{r}
cairo_pdf("figures/spa_vdur_pc1_production.pdf", family = "serif", width = 8, height = 6)
spa_dur_pc1_plot
dev.off()
```

```{r}
spa %>%
  select(pc1)%>%
  summarize(mean = mean(pc1),
            low_sd = mean(pc1)-sd(pc1),
            high_sd = mean(pc1)+sd(pc1))
  
```
```{r}
emt <- emtrends(spa_model, "syllable", var = "v_dur_period")
emt
pairs(emt)
```

```{r}
conditions = data.frame(pc1 = c(-5.51169, -0.612, 4.2868))
spa_dur_pc1_syllable = conditional_effects(spa_model, effects = "v_dur_period:syllable", conditions = conditions)
```

```{r}
spa_dur_pc1_syllable_plot = plot(spa_dur_pc1_syllable, plot = FALSE)[[1]] + labs(title = "Spanish production", x = "Vowel duration (periodic)", y = "Proportion stressed") +
  guides(color=guide_legend(title="Syllable"), fill = 'none') +
  scale_color_discrete(labels=c('Penultimate', 'Ultimate')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")

spa_dur_pc1_syllable_plot$data$cond__ <- ifelse(spa_dur_pc1_syllable_plot$data$cond__ == "1", "PC1 (-1 SD)",
ifelse(spa_dur_pc1_syllable_plot$data$cond__ == "2", "PC1 (mean)",
ifelse(spa_dur_pc1_syllable_plot$data$cond__ == "3", "PC1 (+1 SD)", 99)))


spa_dur_pc1_syllable_plot$data$cond__ <- factor(spa_dur_pc1_syllable_plot$data$cond__, levels = c("PC1 (-1 SD)", "PC1 (mean)", "PC1 (+1 SD)"))

spa_dur_pc1_syllable_plot
```

```{r}
cairo_pdf("figures/spa_dur_pc1_syllable_production.pdf", family = "serif", width = 8, height = 6)
spa_dur_pc1_syllable_plot
dev.off()
```

```{r}
spa %>%
  select(pc2)%>%
  summarize(mean = mean(pc2),
            low_sd = mean(pc2)-sd(pc2),
            high_sd = mean(pc2)+sd(pc2))
  
```
```{r}
conditions = data.frame(pc2 = c(-2.68, -0.168, 2.34))
spa_dur_pc2_syllable = conditional_effects(spa_model, effects = "v_dur_period:syllable", conditions = conditions)
```

```{r}
spa_dur_pc2_syllable_plot = plot(spa_dur_pc2_syllable, plot = FALSE)[[1]] + labs(title = "Spanish production", x = "Vowel duration (periodic)", y = "Proportion stressed") +
  guides(color=guide_legend(title="Syllable"), fill = 'none') +
  scale_color_discrete(labels=c('Penultimate', 'Ultimate')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")

spa_dur_pc2_syllable_plot$data$cond__ <- ifelse(spa_dur_pc2_syllable_plot$data$cond__ == "1", "PC2 (-1 SD)",
ifelse(spa_dur_pc2_syllable_plot$data$cond__ == "2", "PC2 (mean)",
ifelse(spa_dur_pc2_syllable_plot$data$cond__ == "3", "PC2 (+1 SD)", 99)))


spa_dur_pc2_syllable_plot$data$cond__ <- factor(spa_dur_pc2_syllable_plot$data$cond__, levels = c("PC2 (-1 SD)", "PC2 (mean)", "PC2 (+1 SD)"))

spa_dur_pc2_syllable_plot
```
```{r}
cairo_pdf("figures/spa_dur_pc2_syllable_production.pdf", family = "serif", width = 8, height = 6)
spa_dur_pc2_syllable_plot
dev.off()
```

```{r}
emt <- emtrends(spa_model, "syllable", var = "syl_dur")
emt
pairs(emt)
```

```{r}
conditions = data.frame(pc1 = c(-5.51169, -0.612, 4.2868))
spa_syldur_pc1_syllable = conditional_effects(spa_model, effects = "syl_dur:syllable", conditions = conditions)
```

```{r}
spa_syldur_pc1_syllable_plot = plot(spa_syldur_pc1_syllable, plot = FALSE)[[1]] + labs(title = "Spanish production", x = "Syllable duration", y = "Proportion stressed") +
  guides(color=guide_legend(title="Syllable"), fill = 'none') +
  scale_color_discrete(labels=c('Penultimate', 'Ultimate')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")

spa_syldur_pc1_syllable_plot$data$cond__ <- ifelse(spa_syldur_pc1_syllable_plot$data$cond__ == "1", "PC1 (-1 SD)",
ifelse(spa_syldur_pc1_syllable_plot$data$cond__ == "2", "PC1 (mean)",
ifelse(spa_syldur_pc1_syllable_plot$data$cond__ == "3", "PC1 (+1 SD)", 99)))


spa_syldur_pc1_syllable_plot$data$cond__ <- factor(spa_syldur_pc1_syllable_plot$data$cond__, levels = c("PC1 (-1 SD)", "PC1 (mean)", "PC1 (+1 SD)"))

spa_syldur_pc1_syllable_plot
```

```{r}
cairo_pdf("figures/spa_syldur_pc1_syllable_production.pdf", family = "serif", width = 8, height = 6)
spa_syldur_pc1_syllable_plot
dev.off()
```

```{r}
conditions = data.frame(pc2 = c(-2.68, -0.168, 2.34))
spa_syldur_pc2_syllable = conditional_effects(spa_model, effects = "syl_dur:syllable", conditions = conditions)
```

```{r}
spa_syldur_pc2_syllable_plot = plot(spa_syldur_pc2_syllable, plot = FALSE)[[1]] + labs(title = "Spanish production", x = "Syllable duration", y = "Proportion stressed") +
  guides(color=guide_legend(title="Syllable"), fill = 'none') +
  scale_color_discrete(labels=c('Penultimate', 'Ultimate')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")

spa_syldur_pc2_syllable_plot$data$cond__ <- ifelse(spa_syldur_pc2_syllable_plot$data$cond__ == "1", "PC2 (-1 SD)",
ifelse(spa_syldur_pc2_syllable_plot$data$cond__ == "2", "PC2 (mean)",
ifelse(spa_syldur_pc2_syllable_plot$data$cond__ == "3", "PC2 (+1 SD)", 99)))


spa_syldur_pc2_syllable_plot$data$cond__ <- factor(spa_syldur_pc2_syllable_plot$data$cond__, levels = c("PC2 (-1 SD)", "PC2 (mean)", "PC2 (+1 SD)"))

spa_syldur_pc2_syllable_plot
```
```{r}
cairo_pdf("figures/spa_syldur_pc2_syllable_production.pdf", family = "serif", width = 8, height = 6)
spa_syldur_pc2_syllable_plot
dev.off()
```
```{r}
spa_syldur_pc2 = conditional_effects(spa_model, effects = "pc2:syl_dur", int_conditions = "pc2")
```

```{r}
spa_syldur_pc2_plot = plot(spa_syldur_pc2, plot = FALSE)[[1]] + labs(title = "Spanish production", x = "PC2", y = "Proportion stressed") + guides(color=guide_legend(title="Syllable duration"), fill = 'none') +
 scale_color_discrete(breaks = c(-2.52, 0.06, 2.64), labels=c('-1 SD', 'mean', '+1 SD')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")
spa_syldur_pc2_plot
```




```{r}
emt <- emtrends(spa_model, "syllable", var = "pc1")
emt
pairs(emt)
```


```{r}
check = spa %>%
  mutate(pc1_binary = case_when(
    pc1 < 0   ~ "low" ,
    pc1 >0 ~ "high"))

check %>%
  group_by(pc1_binary, syllable, stress) %>% 
  count()
```



