---
title: "Logit models of production data with Bayesian predictive modelling - English language profile, only with reduced words"
author: "Annie Helms (annie_helms@berkeley.edu)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "cairo_pdf", out.height = 600)
options(scipen = 999) # avoid scientific notation
```

Library packages

```{r message = FALSE, warning = FALSE}
library(lmerTest) #mixed effects linear regression
library(dplyr)
library(ggplot2)
library(Cairo)
library(effects)
library(ragg)
library(gridExtra)
library(ggside)
library(sjPlot)
library(emmeans)
library(ggstatsplot)
library(pscl)
library(bayesplot)
library(brms)
library(ggtext)
library(kableExtra) # formats dataframes in html output
```

Set working directory.

```{r message = FALSE, echo = FALSE}
setwd("C:/Users/atarv/Documents/github/diss/production/")
```


```{r}
options(width = 10000)
data = read.csv("data/big_PCA_forR.csv", 
                  stringsAsFactors = TRUE)
head(data)
```

## English production across language profile

```{r}
reduced_words = c('combine', 'compact', 'contract', 'convert', 'convict', 'desert', 'project', 'object', 'record', 'subject')
eng = data %>%
  filter(Language=="eng" & word %in% reduced_words)
head(eng)

```

```{r}
eng_formula = "stress ~ dur_period*lang_profile*syllable + f0*lang_profile*syllable + vowel_periph*lang_profile*syllable + (dur_period * syllable + f0 * syllable + vowel_periph * syllable|partID)"

eng_priors <- get_prior(eng_formula,eng,family=bernoulli())

eng_model <- brm(formula=bf(eng_formula,autocor = ~ 0),data=eng, family=bernoulli(), 
            prior=eng_priors, cores = 8, save_pars = save_pars(all = TRUE), iter=4000)
```

Examine results

```{r}
summary(eng_model)
bayes_R2(eng_model)
```

Visualize results

```{r}
eng_posterior <- as.array(eng_model)  # prepare to plot the brm result
dim(eng_posterior)
dimnames(eng_posterior)$variable[1:30]
```

```{r}
eng_coeff_plot = mcmc_areas(eng_posterior, pars = c("b_dur_period", "b_lang_profilel3_eng", "b_lang_profilemono", "b_syllableult", "b_f0", "b_vowel_periph", "b_dur_period:lang_profilel3_eng", "b_dur_period:lang_profilemono", "b_dur_period:syllableult", "b_lang_profilel3_eng:syllableult", "b_lang_profilemono:syllableult", "b_lang_profilel3_eng:f0", "b_lang_profilemono:f0", "b_syllableult:f0", "b_lang_profilel3_eng:vowel_periph", "b_lang_profilemono:vowel_periph", "b_syllableult:vowel_periph", "b_dur_period:lang_profilel3_eng:syllableult", "b_dur_period:lang_profilemono:syllableult", "b_lang_profilel3_eng:syllableult:f0", "b_lang_profilemono:syllableult:f0", "b_lang_profilel3_eng:syllableult:vowel_periph", "b_lang_profilemono:syllableult:vowel_periph"), 
          prob = 0.8, # 80% intervals
          prob_outer = 0.95, # 95%
          point_est = "median") +
  scale_y_discrete(limits = rev, labels=c("Monolingual:Ultimate syllable:Vowel peripherality", "L3 English:Ultimate syllable:Vowel peripherality", "Monolingual:Ultimate syllable:F0", "L3 English:Ultimate syllable:F0", "Duration (periodic):Monolingual:Ultimate syllable", "Duration (periodic):L3 English:Ultimate syllable", "Ultimate syllable:Vowel peripherality", "Monolingual:Vowel peripherality", "L3 English:Vowel peripherality", "Ultimate syllable:F0", "Monolingual:F0", "L3 English:F0", "Monolingual:Ultimate syllable", "L3 English:Ultimate syllable", "Duration (periodic):Ultimate syllable", "Duration (periodic):Monolingual", "Duration (periodic):L3 English", "Vowel peripherality", "F0", "Ultimate syllable", "Monolingual", "L3 English", "Duration (periodic)"))+
  labs(title = "Coefficients of English production", x ="Coefficient, sd(Stress)")+
  theme(plot.title=element_text(hjust = 0.5))
eng_coeff_plot
```

```{r}
cairo_pdf("figures/eng_lang_coeff.pdf", family = "serif", width = 8, height = 6)
eng_coeff_plot
dev.off()
```

```{r}
eng_lang_syllable_f0 = conditional_effects(eng_model, effects = "f0:syllable", int_conditions = "syllable")
```

```{r}
eng_lang_syllable_f0_plot = plot(eng_lang_syllable_f0, plot = FALSE)[[1]] + labs(title = "English production across syllablee", x = "F0", y = "Proportion stressed") + guides(color=guide_legend(title="Syllable"), fill = 'none') +
  scale_color_discrete(labels=c('Penultimate', 'Ultimate')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")
eng_lang_syllable_f0_plot
```

```{r}
cairo_pdf("figures/eng_lang_syllable_f0_production.pdf", family = "serif", width = 8, height = 6)
eng_lang_syllable_f0_plot
dev.off()
```


```{r}
emt <- emtrends(eng_model, "syllable", var = "vowel_periph")
emt
pairs(emt)
```

```{r}
eng_vowel_syllable = conditional_effects(eng_model, effects = "vowel_periph:syllable", int_conditions = "syllable")
```

```{r}
eng_lang_syllable_vowel_plot = plot(eng_vowel_syllable, plot = FALSE)[[1]] + labs(title = "English production across language profile", x = "Vowel peripherality", y = "Proportion stressed") + guides(color=guide_legend(title="Syllable"), fill = 'none') +
  scale_color_discrete(labels=c('Penultimate', 'Ultimate')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")
eng_lang_syllable_vowel_plot
```


```{r}
emmeans(eng_model, list(pairwise ~ lang_profile*syllable), adjust="tukey")
```

```{r}
eng %>%
  group_by(lang_profile, syllable, stress) %>% 
  count()
```

```{r}
emt <- emtrends(eng_model, "lang_profile", var = "vowel_periph")
emt
pairs(emt)
```

```{r}
eng_vowel_lang = conditional_effects(eng_model, effects = "vowel_periph:lang_profile", int_conditions = "lang_profile")
```

```{r}
eng_vowel_lang_plot = plot(eng_vowel_lang, plot = FALSE)[[1]] + labs(title = "English production across language profile", x = "Vowel peripherality", y = "Proportion stressed") +
  guides(color=guide_legend(title="Language Profile"), fill = 'none') +
  scale_color_discrete(labels=c('L1 English', 'L3 English', 'Monolingual')) +
  # scale_x_discrete(labels=c("L1 English", "L3 English", "Monolingual"))+
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")
eng_vowel_lang_plot
```

```{r}
cairo_pdf("figures/eng_vowel_lang_production.pdf", family = "serif", width = 8, height = 6)
eng_vowel_lang_plot
dev.off()
```

```{r}
emt <- emtrends(eng_model, "lang_profile", var = "dur_period")
emt
pairs(emt)
```

```{r}
emt <- emtrends(eng_model, "syllable", var = "dur_period")
emt
pairs(emt)
```


```{r}
conditions = data.frame(lang_profile = c("mono", "l1_eng", "l3_eng"))
eng_vowel_lang_syllable = conditional_effects(eng_model, effects = "vowel_periph:syllable", conditions = conditions)
```

```{r}
eng_vowel_lang_syllable_plot = plot(eng_vowel_lang_syllable, plot = FALSE)[[1]] + labs(title = "English production across language profile", x = "Vowel peripherality", y = "Proportion stressed") +
  guides(color=guide_legend(title="Syllable"), fill = 'none') +
  scale_color_discrete(labels=c('Penultimate', 'Ultimate')) +
  theme(plot.title=element_text(hjust = 0.5), legend.position = "bottom")

eng_vowel_lang_syllable_plot$data$cond__ <- ifelse(eng_vowel_lang_syllable_plot$data$cond__ == "1", "Monolingual",
ifelse(eng_vowel_lang_syllable_plot$data$cond__ == "2", "L1 English",
ifelse(eng_vowel_lang_syllable_plot$data$cond__ == "3", "L3 English", 99)))

eng_vowel_lang_syllable_plot$data$cond__ <- factor(eng_vowel_lang_syllable_plot$data$cond__, levels = c("Monolingual", "L1 English", "L3 English"))

eng_vowel_lang_syllable_plot
```

```{r}
cairo_pdf("figures/eng_vowel_lang_syllable_production_reduced.pdf", family = "serif", width = 8, height = 6)
eng_vowel_lang_syllable_plot
dev.off()
```


